[package]
name = "reactor_rt"
version = "0.1.0"
authors = ["Clément Fournier <clement.fournier76@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
index_vec = "0.1.2"
itertools = "0.10.1"
bit-set = "0.5"
smallvec = "1.6"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.9"

[[bench]]
name = "savina_pong"
harness = false


[[bin]]
name = "minimal"
path = "examples/Minimal/src/main.rs"
