[package]
name = "reactor_rt"
version = "0.1.0"
authors = ["Clément Fournier <clement.fournier76@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.0.0"
int-enum = "0.4.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "savina_pong"
harness = false
