[package]
name = "rust-reactors"
version = "0.1.0"
authors = ["Clément Fournier <clement.fournier76@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.0.0"
petgraph = "0.5.1"
futures = "0.3"

[[bin]]
name = "example-forwarding"
path = "src/bin/forwarding.rs"

[[bin]]
name = "example-data-sharing"
path = "src/bin/data_sharing.rs"
