[package]
name = "reactor_rt"
version = "0.1.0"
authors = ["Clément Fournier <clement.fournier76@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
index_vec = "0.1.2"
#itertools = "0.10.1"
#bit-set = "0.5"
smallvec = "1.6"
petgraph = "0.6.0"
array-macro = "2.1.0"
atomic_refcell = "0.1.8"
crossbeam = "0.8.1"
regex = { version = "1", optional = true}
assert_matches = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.3"
env_logger = "0.9"
assert_matches = "1.5.0"
regex = { version = "1" }

[features]
# dump the graph to a DOT representation
graph-dump=["regex"]
test-utils=["assert_matches"]

[[bench]]
name = "savina_pong"
harness = false

[profile.bench]
debug = true

