[package]
name = "reactor_rt"
version = "0.1.0"
authors = ["Clément Fournier <clement.fournier76@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
#index_vec = "0.1.2"
itertools = "0.10.1"
bit-set = "0.5"
smallvec = "1.6"
petgraph = "0.6.0"
array-macro = "2.1.0"

[dependencies.index_vec]
# This is my fork, we depend on one new feature bc we use const exprs
# See upstream PR: https://github.com/thomcc/index_vec/pull/7
git = "ssh://git@github.com/oowekyala/index_vec.git"
branch = "const-fns"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.9"
assert_matches = "1.5.0"

[[bench]]
name = "savina_pong"
harness = false


[[bin]]
name = "minimal"
path = "examples/Minimal/src/main.rs"
