name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --all-features
    - name: Run benchmark tests
      run: cargo test --benches --all-features
    # documentation
    - name: Build documentation
      run: cargo doc --frozen --no-deps
    - name: Patch documentation
      run: mv target/doc/reactor_rt target/doc/docs
    - name: Create documentation index
      # cargo doc does not generate a top-level index,
      # create a redirect to our own crate doc
      run: |
        cat << EOF > target/doc/index.html
        <meta http-equiv="refresh" content="0; url=./docs/index.html" />
        EOF
    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_branch: gh_pages
        publish_dir: target/doc
        github_token: ${{ secrets.GITHUB_TOKEN }}

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Check format
      run: cargo fmt --check
