name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run benchmark tests
      run: cargo test --benches --verbose
    - name: Build documentation
      run: cargo doc --verbose
    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_branch: gh_pages
        publish_dir: target/doc
        github_token: ${{ secrets.GITHUB_TOKEN }}
